name: Deploy no Render

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Subindo o Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt
      - name: Executar testes
        run: |
          python -m unittest test_app

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy no Render
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Accept: application/json" \
            "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys"