name: Deploy to Render

on:
  push:
    branches: [ "main" ]  # Ou "master", dependendo do seu repositório

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"  # Altere para a versão que você usa
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          python -m unittest test_app

  deploy:
    needs: test  # Só faz deploy se os testes passarem
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Notify Render
        uses: render-actions/deploy@v1
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}