name: CI + Deploy Flask para Render

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set_tag.outputs.image_tag }}
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Build da imagem Docker
        id: docker_build
        run: |
          docker build -t flask-app .

      - name: Definir tag da imagem
        id: set_tag
        run: |
          echo "image_tag=flask-app" >> $GITHUB_OUTPUT

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Carregar imagem Docker
        run: |
          docker load --input $(docker save -o image.tar flask-app) || true

      - name: Executar testes
        run: |
          docker run --rm \
            -v $(pwd):/app \
            -w /app \
            flask-app \
            sh -c "pip install -r requirements.txt && python -m unittest test_app"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Disparar deploy na Render
        env:
          RENDER_SERVICE_ID: "srv-d0p81oodl3ps73ai525g"
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Accept: application/json" \
            "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys"