name: Deploy no Render

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.build.outputs.image-tag }}
    steps:
      - name:  Checkout do código hehe
        uses: actions/checkout@v4

      - name:  Build da imagem Docker
        id: build
        run: |
          docker build -t flask-app .
          echo "image-tag=flask-app" >> $GITHUB_OUTPUT

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name:  Checkout do código
        uses: actions/checkout@v4

      - name:  Rodar testes no container
        run: |
          docker build -t flask-app .
          docker run --rm flask-app python test_app.py

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy no Render
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Accept: application/json" \
            "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys"